(* This file is auto-generated by generate_attrs tool.
   It should not be modified by hand and it should not be versioned
   (except by continuous integration on the dedicated bootstrap branch). *)
[%%metapackage "metapp"]
[%%metadir "config/.clangml_config.objs/byte"]
type ('expr, 'qual_type, 'declaration_name) t =
  | AMDGPUFlatWorkGroupSize of {
  min: 'expr ;
  max: 'expr } 
  | AMDGPUNumSGPR of int 
  | AMDGPUNumVGPR of int 
  | AMDGPUWavesPerEU of {
  min: 'expr ;
  max: 'expr } 
  | ARMInterrupt of Clang__bindings.clang_ext_arminterruptattr_interrupttype
  
  | AbiTag of string list 
  | AcquireCapability of
  {
  spelling: Clang__bindings.clang_ext_acquirecapability_spelling ;
  args: 'expr list } 
  | AcquireHandle of string 
  | AcquiredAfter of 'expr list 
  | AcquiredBefore of 'expr list 
  | AddressSpace of int 
  | Alias of string 
  | AlignValue of 'expr 
  | Aligned of
  {
  spelling: Clang__bindings.clang_ext_aligned_spelling ;
  alignment_expr: 'expr } 
  | AllocAlign of int 
  | AllocSize of {
  elem_size: int ;
  num_elems: int } 
  | AlwaysInline of Clang__bindings.clang_ext_alwaysinline_spelling 
  | Annotate of string 
  | ArgumentWithTypeTag of
  {
  spelling: Clang__bindings.clang_ext_argumentwithtypetag_spelling ;
  argument_kind: string ;
  argument_idx: int ;
  type_tag_idx: int ;
  is_pointer: bool } 
  | ArmMveAlias of string 
  | AsmLabel of {
  label: string ;
  is_literal_label: bool } 
  | AssertCapability of
  {
  spelling: Clang__bindings.clang_ext_assertcapability_spelling ;
  args: 'expr list } 
  | AssertExclusiveLock of 'expr list 
  | AssertSharedLock of 'expr list 
  | AssumeAligned of {
  alignment: 'expr ;
  offset: 'expr } 
  | Availability of
  {
  platform: string ;
  introduced: Clang__bindings.clang_ext_versiontuple ;
  deprecated: Clang__bindings.clang_ext_versiontuple ;
  obsoleted: Clang__bindings.clang_ext_versiontuple ;
  unavailable: bool ;
  message: string ;
  strict: bool ;
  replacement: string ;
  priority: int } 
  | Blocks of Clang__bindings.clang_ext_blocksattr_blocktype 
  | CFGuard of Clang__bindings.clang_ext_cfguardattr_guardarg 
  | CPUDispatch of string list 
  | CPUSpecific of string list 
  | CUDALaunchBounds of {
  max_threads: 'expr ;
  min_blocks: 'expr } 
  | CallableWhen of Clang__bindings.clang_ext_callablewhenattr_consumedstate
  list 
  | Callback of int list 
  | Capability of
  {
  spelling: Clang__bindings.clang_ext_capability_spelling ;
  name: string } 
  | Cleanup of 'declaration_name 
  | CodeSeg of string 
  | ConstInit of Clang__bindings.clang_ext_constinit_spelling 
  | Constructor of int 
  | Consumable of Clang__bindings.clang_ext_consumableattr_consumedstate 
  | Deprecated of {
  message: string ;
  replacement: string } 
  | Destructor of int 
  | DiagnoseIf of {
  cond: 'expr ;
  message: string } 
  | EnableIf of {
  cond: 'expr ;
  message: string } 
  | EnumExtensibility of Clang__bindings.clang_ext_enumextensibilityattr_kind
  
  | ExclusiveTrylockFunction of {
  success_value: 'expr ;
  args: 'expr list } 
  | ExternalSourceSymbol of
  {
  language: string ;
  defined_in: string ;
  generated_declaration: bool } 
  | Final of Clang__bindings.clang_ext_final_spelling 
  | Format of {
  type_: string ;
  format_idx: int ;
  first_arg: int } 
  | FormatArg of int 
  | GuardedBy of 'expr 
  | IBOutletCollection of 'qual_type 
  | IFunc of string 
  | InitPriority of int 
  | InitSeg of string 
  | LayoutVersion of int 
  | LockReturned of 'expr 
  | LocksExcluded of 'expr list 
  | LoopHint of
  {
  spelling: Clang__bindings.clang_ext_loophint_spelling ;
  option: Clang__bindings.clang_ext_loophintattr_optiontype } 
  | MSInheritance of
  {
  spelling: Clang__bindings.clang_ext_msinheritance_spelling ;
  best_case: bool } 
  | MSP430Interrupt of int 
  | MSVtorDisp of int 
  | MaxFieldAlignment of int 
  | MinVectorWidth of int 
  | MipsInterrupt of
  Clang__bindings.clang_ext_mipsinterruptattr_interrupttype 
  | MipsLongCall of Clang__bindings.clang_ext_mipslongcall_spelling 
  | MipsShortCall of Clang__bindings.clang_ext_mipsshortcall_spelling 
  | Mode of string 
  | NoBuiltin of string list 
  | NoSanitize of string list 
  | NonNull of int list 
  | OMPAllocateDecl of
  {
  allocator_type:
    Clang__bindings.clang_ext_ompallocatedeclattr_allocatortypety ;
  allocator: 'expr } 
  | OMPCaptureKind of int 
  | OMPDeclareSimdDecl of
  {
  branch_state:
    Clang__bindings.clang_ext_ompdeclaresimddeclattr_branchstatety ;
  simdlen: 'expr ;
  uniforms: 'expr list ;
  aligneds: 'expr list ;
  alignments: 'expr list ;
  linears: 'expr list ;
  modifiers: int list ;
  steps: 'expr list } 
  | OMPDeclareTargetDecl of
  Clang__bindings.clang_ext_ompdeclaretargetdeclattr_maptypety 
  | OMPDeclareVariant of
  {
  variant_func_ref: 'expr ;
  scores: 'expr list ;
  ctx_selector_sets: int list ;
  ctx_selectors: int list ;
  impl_vendors: string list ;
  device_kinds: string list } 
  | OMPReferencedVar of 'expr 
  | ObjCBridge of string 
  | ObjCBridgeMutable of string 
  | ObjCBridgeRelated of
  {
  related_class: string ;
  class_method: string ;
  instance_method: string } 
  | ObjCGC of string 
  | ObjCMethodFamily of
  Clang__bindings.clang_ext_objcmethodfamilyattr_familykind 
  | ObjCOwnership of string 
  | ObjCRuntimeName of string 
  | OpenCLAccess of Clang__bindings.clang_ext_openclaccess_spelling 
  | OpenCLConstantAddressSpace of
  Clang__bindings.clang_ext_openclconstantaddressspace_spelling 
  | OpenCLGenericAddressSpace of
  Clang__bindings.clang_ext_openclgenericaddressspace_spelling 
  | OpenCLGlobalAddressSpace of
  Clang__bindings.clang_ext_openclglobaladdressspace_spelling 
  | OpenCLIntelReqdSubGroupSize of int 
  | OpenCLLocalAddressSpace of
  Clang__bindings.clang_ext_opencllocaladdressspace_spelling 
  | OpenCLPrivateAddressSpace of
  Clang__bindings.clang_ext_openclprivateaddressspace_spelling 
  | OpenCLUnrollHint of int 
  | Owner of 'qual_type 
  | Ownership of
  {
  spelling: Clang__bindings.clang_ext_ownership_spelling ;
  module_: string ;
  args: int list } 
  | ParamTypestate of
  Clang__bindings.clang_ext_paramtypestateattr_consumedstate 
  | PassObjectSize of
  {
  spelling: Clang__bindings.clang_ext_passobjectsize_spelling ;
  type_: int } 
  | PatchableFunctionEntry of {
  count: int ;
  offset: int } 
  | Pcs of Clang__bindings.clang_ext_pcsattr_pcstype 
  | Pointer of 'qual_type 
  | PragmaClangBSSSection of string 
  | PragmaClangDataSection of string 
  | PragmaClangRelroSection of string 
  | PragmaClangRodataSection of string 
  | PragmaClangTextSection of string 
  | PtGuardedBy of 'expr 
  | RISCVInterrupt of
  Clang__bindings.clang_ext_riscvinterruptattr_interrupttype 
  | ReleaseCapability of
  {
  spelling: Clang__bindings.clang_ext_releasecapability_spelling ;
  args: 'expr list } 
  | ReleaseHandle of string 
  | ReqdWorkGroupSize of {
  x_dim: int ;
  y_dim: int ;
  z_dim: int } 
  | RequiresCapability of
  {
  spelling: Clang__bindings.clang_ext_requirescapability_spelling ;
  args: 'expr list } 
  | Restrict of Clang__bindings.clang_ext_restrict_spelling 
  | ReturnTypestate of
  Clang__bindings.clang_ext_returntypestateattr_consumedstate 
  | Section of
  {
  spelling: Clang__bindings.clang_ext_section_spelling ;
  name: string } 
  | Sentinel of {
  sentinel: int ;
  null_pos: int } 
  | SetTypestate of Clang__bindings.clang_ext_settypestateattr_consumedstate
  
  | SharedTrylockFunction of {
  success_value: 'expr ;
  args: 'expr list } 
  | Suppress of string list 
  | TLSModel of string 
  | Target of string 
  | TestTypestate of
  Clang__bindings.clang_ext_testtypestateattr_consumedstate 
  | TryAcquireCapability of
  {
  spelling: Clang__bindings.clang_ext_tryacquirecapability_spelling ;
  success_value: 'expr ;
  args: 'expr list } 
  | TypeTagForDatatype of
  {
  argument_kind: string ;
  matching_ctype: 'qual_type ;
  layout_compatible: bool ;
  must_be_null: bool } 
  | TypeVisibility of
  Clang__bindings.clang_ext_typevisibilityattr_visibilitytype 
  | Unavailable of string 
  | Unused of Clang__bindings.clang_ext_unused_spelling 
  | UseHandle of string 
  | Uuid of string 
  | VecTypeHint of 'qual_type 
  | Visibility of Clang__bindings.clang_ext_visibilityattr_visibilitytype 
  | WarnUnusedResult of
  {
  spelling: Clang__bindings.clang_ext_warnunusedresult_spelling ;
  message: string } 
  | WeakRef of string 
  | WebAssemblyExportName of string 
  | WebAssemblyImportModule of string 
  | WebAssemblyImportName of string 
  | WorkGroupSizeHint of {
  x_dim: int ;
  y_dim: int ;
  z_dim: int } 
  | XRayInstrument of Clang__bindings.clang_ext_xrayinstrument_spelling 
  | XRayLogArgs of int 
  | Other of Clang__bindings.clang_ext_attrkind [@@deriving refl]
[%%meta
  Metapp.filter.structure_item Metapp.filter
    ([%stri
       let convert cursor expr_of_cxcursor of_type_loc
         convert_declaration_name =
         match Clang__bindings.ext_attr_get_kind cursor with
         | ((AMDGPUFlatWorkGroupSize)[@if
                                       [%meta
                                         Metapp.Exp.of_bool
                                           (Clangml_config.version.major >= 9)]])
             ->
             AMDGPUFlatWorkGroupSize
               {
                 min =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_min cursor));
                 max =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_max cursor))
               }
         | ((AMDGPUNumSGPR)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (((Clangml_config.version.major),
                                    (Clangml_config.version.minor)) >= 
                                    (3, 6))]])
             ->
             AMDGPUNumSGPR
               (Clang__bindings.ext_amdgpunum_sgprattr_get_num_sgpr cursor)
         | ((AMDGPUNumVGPR)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (((Clangml_config.version.major),
                                    (Clangml_config.version.minor)) >= 
                                    (3, 6))]])
             ->
             AMDGPUNumVGPR
               (Clang__bindings.ext_amdgpunum_vgprattr_get_num_vgpr cursor)
         | ((AMDGPUWavesPerEU)[@if
                                [%meta
                                  Metapp.Exp.of_bool
                                    (Clangml_config.version.major >= 9)]])
             ->
             AMDGPUWavesPerEU
               {
                 min =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_min cursor));
                 max =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_max cursor))
               }
         | ARMInterrupt ->
             ARMInterrupt
               (Clang__bindings.ext_arminterrupt_attr_get_interrupt cursor)
         | ((AbiTag)[@if
                      [%meta
                        Metapp.Exp.of_bool
                          (((Clangml_config.version.major),
                             (Clangml_config.version.minor)) >= (3, 9))]])
             ->
             AbiTag
               (Clang__utils.list_of_iter
                  (Clang__bindings.ext_abi_tag_attr_get_tags cursor))
         | ((AcquireCapability)[@if
                                 [%meta
                                   Metapp.Exp.of_bool
                                     (((Clangml_config.version.major),
                                        (Clangml_config.version.minor)) >=
                                        (3, 5))]])
             ->
             AcquireCapability
               {
                 spelling =
                   (Clang__bindings.ext_acquire_capability_get_spelling
                      cursor);
                 args =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_acquire_capability_attr_get_args
                          cursor))
                      |> (List.map expr_of_cxcursor))
               }
         | ((AcquireHandle)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (Clangml_config.version.major >= 10)]])
             ->
             AcquireHandle (Clang__bindings.ext_attrs_get_handle_type cursor)
         | AcquiredAfter ->
             AcquiredAfter
               ((Clang__utils.list_of_iter
                   (Clang__bindings.ext_acquire_capability_attr_get_args
                      cursor))
                  |> (List.map expr_of_cxcursor))
         | AcquiredBefore ->
             AcquiredBefore
               ((Clang__utils.list_of_iter
                   (Clang__bindings.ext_acquire_capability_attr_get_args
                      cursor))
                  |> (List.map expr_of_cxcursor))
         | ((AddressSpace)[@if
                            [%meta
                              Metapp.Exp.of_bool
                                (Clangml_config.version.major >= 8)]])
             ->
             AddressSpace
               (Clang__bindings.ext_address_space_attr_get_address_space
                  cursor)
         | Alias -> Alias (Clang__bindings.ext_attrs_get_aliasee cursor)
         | ((AlignValue)[@if
                          [%meta
                            Metapp.Exp.of_bool
                              (((Clangml_config.version.major),
                                 (Clangml_config.version.minor)) >= (3, 6))]])
             ->
             AlignValue
               (expr_of_cxcursor
                  (Clang__bindings.ext_attrs_get_alignment cursor))
         | Aligned ->
             Aligned
               {
                 spelling = (Clang__bindings.ext_aligned_get_spelling cursor);
                 alignment_expr =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_aligned_attr_get_alignment_expr
                         cursor))
               }
         | ((AllocAlign)[@if
                          [%meta
                            Metapp.Exp.of_bool
                              (Clangml_config.version.major >= 5)]])
             ->
             AllocAlign
               (Clang__bindings.ext_alloc_align_attr_get_param_index cursor)
         | ((AllocSize)[@if
                         [%meta
                           Metapp.Exp.of_bool
                             (Clangml_config.version.major >= 4)]])
             ->
             AllocSize
               {
                 elem_size =
                   (Clang__bindings.ext_alloc_size_attr_get_elem_size_param
                      cursor);
                 num_elems =
                   (Clang__bindings.ext_alloc_size_attr_get_num_elems_param
                      cursor)
               }
         | AlwaysInline ->
             AlwaysInline
               (Clang__bindings.ext_always_inline_get_spelling cursor)
         | Annotate ->
             Annotate
               (Clang__bindings.ext_annotate_attr_get_annotation cursor)
         | ArgumentWithTypeTag ->
             ArgumentWithTypeTag
               {
                 spelling =
                   (Clang__bindings.ext_argument_with_type_tag_get_spelling
                      cursor);
                 argument_kind =
                   (Clang__bindings.ext_attrs_get_argument_kind cursor);
                 argument_idx =
                   (Clang__bindings.ext_argument_with_type_tag_attr_get_argument_idx
                      cursor);
                 type_tag_idx =
                   (Clang__bindings.ext_argument_with_type_tag_attr_get_type_tag_idx
                      cursor);
                 is_pointer =
                   (Clang__bindings.ext_argument_with_type_tag_attr_get_is_pointer
                      cursor)
               }
         | ((ArmMveAlias)[@if
                           [%meta
                             Metapp.Exp.of_bool
                               (Clangml_config.version.major >= 10)]])
             ->
             ArmMveAlias
               (Clang__bindings.ext_arm_mve_alias_attr_get_builtin_name
                  cursor)
         | ((AsmLabel)[@if
                        [%meta
                          Metapp.Exp.of_bool
                            (Clangml_config.version.major >= 10)]])
             ->
             AsmLabel
               {
                 label =
                   (Clang__bindings.ext_asm_label_attr_get_label cursor);
                 is_literal_label =
                   (Clang__bindings.ext_asm_label_attr_get_is_literal_label
                      cursor)
               }
         | ((AssertCapability)[@if
                                [%meta
                                  Metapp.Exp.of_bool
                                    (Clangml_config.version.major >= 6)]])
             ->
             AssertCapability
               {
                 spelling =
                   (Clang__bindings.ext_assert_capability_get_spelling cursor);
                 args =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_acquire_capability_attr_get_args
                          cursor))
                      |> (List.map expr_of_cxcursor))
               }
         | AssertExclusiveLock ->
             AssertExclusiveLock
               ((Clang__utils.list_of_iter
                   (Clang__bindings.ext_acquire_capability_attr_get_args
                      cursor))
                  |> (List.map expr_of_cxcursor))
         | AssertSharedLock ->
             AssertSharedLock
               ((Clang__utils.list_of_iter
                   (Clang__bindings.ext_acquire_capability_attr_get_args
                      cursor))
                  |> (List.map expr_of_cxcursor))
         | ((AssumeAligned)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (((Clangml_config.version.major),
                                    (Clangml_config.version.minor)) >= 
                                    (3, 6))]])
             ->
             AssumeAligned
               {
                 alignment =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_alignment cursor));
                 offset =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_assume_aligned_attr_get_offset
                         cursor))
               }
         | ((Availability)[@if
                            [%meta
                              Metapp.Exp.of_bool
                                (Clangml_config.version.major >= 9)]])
             ->
             Availability
               {
                 platform =
                   (Clang__bindings.ext_availability_attr_get_platform cursor);
                 introduced =
                   (Clang__bindings.ext_availability_attr_get_introduced
                      cursor);
                 deprecated =
                   (Clang__bindings.ext_availability_attr_get_deprecated
                      cursor);
                 obsoleted =
                   (Clang__bindings.ext_availability_attr_get_obsoleted
                      cursor);
                 unavailable =
                   (Clang__bindings.ext_availability_attr_get_unavailable
                      cursor);
                 message = (Clang__bindings.ext_attrs_get_message cursor);
                 strict =
                   (Clang__bindings.ext_availability_attr_get_strict cursor);
                 replacement =
                   (Clang__bindings.ext_attrs_get_replacement cursor);
                 priority = (Clang__bindings.ext_attrs_get_priority cursor)
               }
         | Blocks -> Blocks (Clang__bindings.ext_blocks_attr_get_type cursor)
         | ((CFGuard)[@if
                       [%meta
                         Metapp.Exp.of_bool
                           (Clangml_config.version.major >= 10)]])
             -> CFGuard (Clang__bindings.ext_cfguard_attr_get_guard cursor)
         | ((CPUDispatch)[@if
                           [%meta
                             Metapp.Exp.of_bool
                               (Clangml_config.version.major >= 7)]])
             ->
             CPUDispatch
               (Clang__utils.list_of_iter
                  (Clang__bindings.ext_attrs_get_cpus cursor))
         | ((CPUSpecific)[@if
                           [%meta
                             Metapp.Exp.of_bool
                               (Clangml_config.version.major >= 7)]])
             ->
             CPUSpecific
               (Clang__utils.list_of_iter
                  (Clang__bindings.ext_attrs_get_cpus cursor))
         | ((CUDALaunchBounds)[@if
                                [%meta
                                  Metapp.Exp.of_bool
                                    (((Clangml_config.version.major),
                                       (Clangml_config.version.minor)) >=
                                       (3, 7))]])
             ->
             CUDALaunchBounds
               {
                 max_threads =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_cudalaunch_bounds_attr_get_max_threads
                         cursor));
                 min_blocks =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_cudalaunch_bounds_attr_get_min_blocks
                         cursor))
               }
         | ((CallableWhen)[@if
                            [%meta
                              Metapp.Exp.of_bool
                                (((Clangml_config.version.major),
                                   (Clangml_config.version.minor)) >= 
                                   (3, 5))]])
             ->
             CallableWhen
               (Clang__utils.list_of_iter
                  (Clang__bindings.ext_callable_when_attr_get_callable_states
                     cursor))
         | ((Callback)[@if
                        [%meta
                          Metapp.Exp.of_bool
                            (Clangml_config.version.major >= 9)]])
             ->
             Callback
               (Clang__utils.list_of_iter
                  (Clang__bindings.ext_callback_attr_get_encoding cursor))
         | ((Capability)[@if
                          [%meta
                            Metapp.Exp.of_bool
                              (((Clangml_config.version.major),
                                 (Clangml_config.version.minor)) >= (3, 5))]])
             ->
             Capability
               {
                 spelling =
                   (Clang__bindings.ext_capability_get_spelling cursor);
                 name = (Clang__bindings.ext_attrs_get_name cursor)
               }
         | Cleanup ->
             Cleanup
               (convert_declaration_name
                  (Clang__bindings.ext_cleanup_attr_get_function_decl cursor))
         | ((CodeSeg)[@if
                       [%meta
                         Metapp.Exp.of_bool
                           (Clangml_config.version.major >= 7)]])
             -> CodeSeg (Clang__bindings.ext_attrs_get_name cursor)
         | ((ConstInit)[@if
                         [%meta
                           Metapp.Exp.of_bool
                             (Clangml_config.version.major >= 10)]])
             ->
             ConstInit (Clang__bindings.ext_const_init_get_spelling cursor)
         | Constructor ->
             Constructor (Clang__bindings.ext_attrs_get_priority cursor)
         | Consumable ->
             Consumable
               (Clang__bindings.ext_consumable_attr_get_default_state cursor)
         | ((Deprecated)[@if
                          [%meta
                            Metapp.Exp.of_bool
                              (((Clangml_config.version.major),
                                 (Clangml_config.version.minor)) >= (3, 9))]])
             ->
             Deprecated
               {
                 message = (Clang__bindings.ext_attrs_get_message cursor);
                 replacement =
                   (Clang__bindings.ext_attrs_get_replacement cursor)
               }
         | Destructor ->
             Destructor (Clang__bindings.ext_attrs_get_priority cursor)
         | ((DiagnoseIf)[@if
                          [%meta
                            Metapp.Exp.of_bool
                              (Clangml_config.version.major >= 4)]])
             ->
             DiagnoseIf
               {
                 cond =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_cond cursor));
                 message = (Clang__bindings.ext_attrs_get_message cursor)
               }
         | ((EnableIf)[@if
                        [%meta
                          Metapp.Exp.of_bool
                            (((Clangml_config.version.major),
                               (Clangml_config.version.minor)) >= (3, 5))]])
             ->
             EnableIf
               {
                 cond =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_cond cursor));
                 message = (Clang__bindings.ext_attrs_get_message cursor)
               }
         | ((EnumExtensibility)[@if
                                 [%meta
                                   Metapp.Exp.of_bool
                                     (Clangml_config.version.major >= 5)]])
             ->
             EnumExtensibility
               (Clang__bindings.ext_enum_extensibility_attr_get_extensibility
                  cursor)
         | ExclusiveTrylockFunction ->
             ExclusiveTrylockFunction
               {
                 success_value =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_success_value cursor));
                 args =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_acquire_capability_attr_get_args
                          cursor))
                      |> (List.map expr_of_cxcursor))
               }
         | ((ExternalSourceSymbol)[@if
                                    [%meta
                                      Metapp.Exp.of_bool
                                        (Clangml_config.version.major >= 5)]])
             ->
             ExternalSourceSymbol
               {
                 language =
                   (Clang__bindings.ext_external_source_symbol_attr_get_language
                      cursor);
                 defined_in =
                   (Clang__bindings.ext_external_source_symbol_attr_get_defined_in
                      cursor);
                 generated_declaration =
                   (Clang__bindings.ext_external_source_symbol_attr_get_generated_declaration
                      cursor)
               }
         | Final -> Final (Clang__bindings.ext_final_get_spelling cursor)
         | Format ->
             Format
               {
                 type_ = (Clang__bindings.ext_format_attr_get_type cursor);
                 format_idx =
                   (Clang__bindings.ext_format_attr_get_format_idx cursor);
                 first_arg =
                   (Clang__bindings.ext_format_attr_get_first_arg cursor)
               }
         | FormatArg ->
             FormatArg
               (Clang__bindings.ext_format_arg_attr_get_format_idx cursor)
         | GuardedBy ->
             GuardedBy
               (expr_of_cxcursor (Clang__bindings.ext_attrs_get_arg cursor))
         | IBOutletCollection ->
             IBOutletCollection
               (of_type_loc
                  (Clang__bindings.ext_iboutlet_collection_attr_get_interface
                     cursor))
         | ((IFunc)[@if
                     [%meta
                       Metapp.Exp.of_bool
                         (((Clangml_config.version.major),
                            (Clangml_config.version.minor)) >= (3, 9))]])
             -> IFunc (Clang__bindings.ext_ifunc_attr_get_resolver cursor)
         | InitPriority ->
             InitPriority
               (Clang__bindings.ext_init_priority_attr_get_priority cursor)
         | ((InitSeg)[@if
                       [%meta
                         Metapp.Exp.of_bool
                           (((Clangml_config.version.major),
                              (Clangml_config.version.minor)) >= (3, 5))]])
             ->
             InitSeg (Clang__bindings.ext_init_seg_attr_get_section cursor)
         | ((LayoutVersion)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (((Clangml_config.version.major),
                                    (Clangml_config.version.minor)) >= 
                                    (3, 9))]])
             ->
             LayoutVersion
               (Clang__bindings.ext_layout_version_attr_get_version cursor)
         | LockReturned ->
             LockReturned
               (expr_of_cxcursor (Clang__bindings.ext_attrs_get_arg cursor))
         | LocksExcluded ->
             LocksExcluded
               ((Clang__utils.list_of_iter
                   (Clang__bindings.ext_acquire_capability_attr_get_args
                      cursor))
                  |> (List.map expr_of_cxcursor))
         | ((LoopHint)[@if
                        [%meta
                          Metapp.Exp.of_bool
                            (Clangml_config.version.major >= 10)]])
             ->
             LoopHint
               {
                 spelling =
                   (Clang__bindings.ext_loop_hint_get_spelling cursor);
                 option =
                   (Clang__bindings.ext_loop_hint_attr_get_option cursor)
               }
         | ((MSInheritance)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (((Clangml_config.version.major),
                                    (Clangml_config.version.minor)) >= 
                                    (3, 5))]])
             ->
             MSInheritance
               {
                 spelling =
                   (Clang__bindings.ext_msinheritance_get_spelling cursor);
                 best_case =
                   (Clang__bindings.ext_msinheritance_attr_get_best_case
                      cursor)
               }
         | MSP430Interrupt ->
             MSP430Interrupt
               (Clang__bindings.ext_msp430_interrupt_attr_get_number cursor)
         | ((MSVtorDisp)[@if
                          [%meta
                            Metapp.Exp.of_bool
                              (((Clangml_config.version.major),
                                 (Clangml_config.version.minor)) >= (3, 5))]])
             ->
             MSVtorDisp (Clang__bindings.ext_msvtor_disp_attr_get_vdm cursor)
         | MaxFieldAlignment ->
             MaxFieldAlignment
               (Clang__bindings.ext_max_field_alignment_attr_get_alignment
                  cursor)
         | ((MinVectorWidth)[@if
                              [%meta
                                Metapp.Exp.of_bool
                                  (Clangml_config.version.major >= 7)]])
             ->
             MinVectorWidth
               (Clang__bindings.ext_min_vector_width_attr_get_vector_width
                  cursor)
         | ((MipsInterrupt)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (((Clangml_config.version.major),
                                    (Clangml_config.version.minor)) >= 
                                    (3, 8))]])
             ->
             MipsInterrupt
               (Clang__bindings.ext_mips_interrupt_attr_get_interrupt cursor)
         | ((MipsLongCall)[@if
                            [%meta
                              Metapp.Exp.of_bool
                                (Clangml_config.version.major >= 6)]])
             ->
             MipsLongCall
               (Clang__bindings.ext_mips_long_call_get_spelling cursor)
         | ((MipsShortCall)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (Clangml_config.version.major >= 6)]])
             ->
             MipsShortCall
               (Clang__bindings.ext_mips_short_call_get_spelling cursor)
         | Mode -> Mode (Clang__bindings.ext_mode_attr_get_mode cursor)
         | ((NoBuiltin)[@if
                         [%meta
                           Metapp.Exp.of_bool
                             (Clangml_config.version.major >= 10)]])
             ->
             NoBuiltin
               (Clang__utils.list_of_iter
                  (Clang__bindings.ext_no_builtin_attr_get_builtin_names
                     cursor))
         | ((NoSanitize)[@if
                          [%meta
                            Metapp.Exp.of_bool
                              (((Clangml_config.version.major),
                                 (Clangml_config.version.minor)) >= (3, 7))]])
             ->
             NoSanitize
               (Clang__utils.list_of_iter
                  (Clang__bindings.ext_no_sanitize_attr_get_sanitizers cursor))
         | NonNull ->
             NonNull
               (Clang__utils.list_of_iter
                  (Clang__bindings.ext_non_null_attr_get_args cursor))
         | ((OMPAllocateDecl)[@if
                               [%meta
                                 Metapp.Exp.of_bool
                                   (Clangml_config.version.major >= 9)]])
             ->
             OMPAllocateDecl
               {
                 allocator_type =
                   (Clang__bindings.ext_ompallocate_decl_attr_get_allocator_type
                      cursor);
                 allocator =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_ompallocate_decl_attr_get_allocator
                         cursor))
               }
         | ((OMPCaptureKind)[@if
                              [%meta
                                Metapp.Exp.of_bool
                                  (Clangml_config.version.major >= 6)]])
             ->
             OMPCaptureKind
               (Clang__bindings.ext_ompcapture_kind_attr_get_capture_kind
                  cursor)
         | ((OMPDeclareSimdDecl)[@if
                                  [%meta
                                    Metapp.Exp.of_bool
                                      (((Clangml_config.version.major),
                                         (Clangml_config.version.minor)) >=
                                         (3, 9))]])
             ->
             OMPDeclareSimdDecl
               {
                 branch_state =
                   (Clang__bindings.ext_ompdeclare_simd_decl_attr_get_branch_state
                      cursor);
                 simdlen =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_ompdeclare_simd_decl_attr_get_simdlen
                         cursor));
                 uniforms =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_ompdeclare_simd_decl_attr_get_uniforms
                          cursor))
                      |> (List.map expr_of_cxcursor));
                 aligneds =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_ompdeclare_simd_decl_attr_get_aligneds
                          cursor))
                      |> (List.map expr_of_cxcursor));
                 alignments =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_ompdeclare_simd_decl_attr_get_alignments
                          cursor))
                      |> (List.map expr_of_cxcursor));
                 linears =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_ompdeclare_simd_decl_attr_get_linears
                          cursor))
                      |> (List.map expr_of_cxcursor));
                 modifiers =
                   (Clang__utils.list_of_iter
                      (Clang__bindings.ext_ompdeclare_simd_decl_attr_get_modifiers
                         cursor));
                 steps =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_ompdeclare_simd_decl_attr_get_steps
                          cursor))
                      |> (List.map expr_of_cxcursor))
               }
         | ((OMPDeclareTargetDecl)[@if
                                    [%meta
                                      Metapp.Exp.of_bool
                                        (((Clangml_config.version.major),
                                           (Clangml_config.version.minor)) >=
                                           (3, 9))]])
             ->
             OMPDeclareTargetDecl
               (Clang__bindings.ext_ompdeclare_target_decl_attr_get_map_type
                  cursor)
         | ((OMPDeclareVariant)[@if
                                 [%meta
                                   Metapp.Exp.of_bool
                                     (Clangml_config.version.major >= 10)]])
             ->
             OMPDeclareVariant
               {
                 variant_func_ref =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_ompdeclare_variant_attr_get_variant_func_ref
                         cursor));
                 scores =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_ompdeclare_variant_attr_get_scores
                          cursor))
                      |> (List.map expr_of_cxcursor));
                 ctx_selector_sets =
                   (Clang__utils.list_of_iter
                      (Clang__bindings.ext_ompdeclare_variant_attr_get_ctx_selector_sets
                         cursor));
                 ctx_selectors =
                   (Clang__utils.list_of_iter
                      (Clang__bindings.ext_ompdeclare_variant_attr_get_ctx_selectors
                         cursor));
                 impl_vendors =
                   (Clang__utils.list_of_iter
                      (Clang__bindings.ext_ompdeclare_variant_attr_get_impl_vendors
                         cursor));
                 device_kinds =
                   (Clang__utils.list_of_iter
                      (Clang__bindings.ext_ompdeclare_variant_attr_get_device_kinds
                         cursor))
               }
         | ((OMPReferencedVar)[@if
                                [%meta
                                  Metapp.Exp.of_bool
                                    (Clangml_config.version.major >= 7)]])
             ->
             OMPReferencedVar
               (expr_of_cxcursor
                  (Clang__bindings.ext_ompreferenced_var_attr_get_ref cursor))
         | ObjCBridge ->
             ObjCBridge (Clang__bindings.ext_attrs_get_bridged_type cursor)
         | ((ObjCBridgeMutable)[@if
                                 [%meta
                                   Metapp.Exp.of_bool
                                     (((Clangml_config.version.major),
                                        (Clangml_config.version.minor)) >=
                                        (3, 5))]])
             ->
             ObjCBridgeMutable
               (Clang__bindings.ext_attrs_get_bridged_type cursor)
         | ((ObjCBridgeRelated)[@if
                                 [%meta
                                   Metapp.Exp.of_bool
                                     (((Clangml_config.version.major),
                                        (Clangml_config.version.minor)) >=
                                        (3, 5))]])
             ->
             ObjCBridgeRelated
               {
                 related_class =
                   (Clang__bindings.ext_obj_cbridge_related_attr_get_related_class
                      cursor);
                 class_method =
                   (Clang__bindings.ext_obj_cbridge_related_attr_get_class_method
                      cursor);
                 instance_method =
                   (Clang__bindings.ext_obj_cbridge_related_attr_get_instance_method
                      cursor)
               }
         | ((ObjCGC)[@if
                      [%meta
                        Metapp.Exp.of_bool
                          (Clangml_config.version.major >= 8)]])
             -> ObjCGC (Clang__bindings.ext_attrs_get_kind cursor)
         | ObjCMethodFamily ->
             ObjCMethodFamily
               (Clang__bindings.ext_obj_cmethod_family_attr_get_family cursor)
         | ((ObjCOwnership)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (Clangml_config.version.major >= 8)]])
             -> ObjCOwnership (Clang__bindings.ext_attrs_get_kind cursor)
         | ((ObjCRuntimeName)[@if
                               [%meta
                                 Metapp.Exp.of_bool
                                   (((Clangml_config.version.major),
                                      (Clangml_config.version.minor)) >=
                                      (3, 5))]])
             ->
             ObjCRuntimeName
               (Clang__bindings.ext_obj_cruntime_name_attr_get_metadata_name
                  cursor)
         | ((OpenCLAccess)[@if
                            [%meta
                              Metapp.Exp.of_bool
                                (((Clangml_config.version.major),
                                   (Clangml_config.version.minor)) >= 
                                   (3, 9))]])
             ->
             OpenCLAccess
               (Clang__bindings.ext_open_claccess_get_spelling cursor)
         | ((OpenCLConstantAddressSpace)[@if
                                          [%meta
                                            Metapp.Exp.of_bool
                                              (Clangml_config.version.major
                                                 >= 8)]])
             ->
             OpenCLConstantAddressSpace
               (Clang__bindings.ext_open_clconstant_address_space_get_spelling
                  cursor)
         | ((OpenCLGenericAddressSpace)[@if
                                         [%meta
                                           Metapp.Exp.of_bool
                                             (Clangml_config.version.major >=
                                                8)]])
             ->
             OpenCLGenericAddressSpace
               (Clang__bindings.ext_open_clgeneric_address_space_get_spelling
                  cursor)
         | ((OpenCLGlobalAddressSpace)[@if
                                        [%meta
                                          Metapp.Exp.of_bool
                                            (Clangml_config.version.major >=
                                               8)]])
             ->
             OpenCLGlobalAddressSpace
               (Clang__bindings.ext_open_clglobal_address_space_get_spelling
                  cursor)
         | ((OpenCLIntelReqdSubGroupSize)[@if
                                           [%meta
                                             Metapp.Exp.of_bool
                                               (Clangml_config.version.major
                                                  >= 5)]])
             ->
             OpenCLIntelReqdSubGroupSize
               (Clang__bindings.ext_open_clintel_reqd_sub_group_size_attr_get_sub_group_size
                  cursor)
         | ((OpenCLLocalAddressSpace)[@if
                                       [%meta
                                         Metapp.Exp.of_bool
                                           (Clangml_config.version.major >= 8)]])
             ->
             OpenCLLocalAddressSpace
               (Clang__bindings.ext_open_cllocal_address_space_get_spelling
                  cursor)
         | ((OpenCLPrivateAddressSpace)[@if
                                         [%meta
                                           Metapp.Exp.of_bool
                                             (Clangml_config.version.major >=
                                                8)]])
             ->
             OpenCLPrivateAddressSpace
               (Clang__bindings.ext_open_clprivate_address_space_get_spelling
                  cursor)
         | ((OpenCLUnrollHint)[@if
                                [%meta
                                  Metapp.Exp.of_bool
                                    (((Clangml_config.version.major),
                                       (Clangml_config.version.minor)) >=
                                       (3, 9))]])
             ->
             OpenCLUnrollHint
               (Clang__bindings.ext_open_clunroll_hint_attr_get_unroll_hint
                  cursor)
         | ((Owner)[@if
                     [%meta
                       Metapp.Exp.of_bool
                         (Clangml_config.version.major >= 10)]])
             ->
             Owner
               (of_type_loc (Clang__bindings.ext_attrs_get_deref_type cursor))
         | ((Ownership)[@if
                         [%meta
                           Metapp.Exp.of_bool
                             (((Clangml_config.version.major),
                                (Clangml_config.version.minor)) >= (3, 7))]])
             ->
             Ownership
               {
                 spelling =
                   (Clang__bindings.ext_ownership_get_spelling cursor);
                 module_ =
                   (Clang__bindings.ext_ownership_attr_get_module cursor);
                 args =
                   (Clang__utils.list_of_iter
                      (Clang__bindings.ext_non_null_attr_get_args cursor))
               }
         | ParamTypestate ->
             ParamTypestate
               (Clang__bindings.ext_param_typestate_attr_get_param_state
                  cursor)
         | ((PassObjectSize)[@if
                              [%meta
                                Metapp.Exp.of_bool
                                  (((Clangml_config.version.major),
                                     (Clangml_config.version.minor)) >=
                                     (3, 8))]])
             ->
             PassObjectSize
               {
                 spelling =
                   (Clang__bindings.ext_pass_object_size_get_spelling cursor);
                 type_ =
                   (Clang__bindings.ext_pass_object_size_attr_get_type cursor)
               }
         | ((PatchableFunctionEntry)[@if
                                      [%meta
                                        Metapp.Exp.of_bool
                                          (Clangml_config.version.major >= 10)]])
             ->
             PatchableFunctionEntry
               {
                 count =
                   (Clang__bindings.ext_patchable_function_entry_attr_get_count
                      cursor);
                 offset =
                   (Clang__bindings.ext_patchable_function_entry_attr_get_offset
                      cursor)
               }
         | Pcs -> Pcs (Clang__bindings.ext_pcs_attr_get_pcs cursor)
         | ((Pointer)[@if
                       [%meta
                         Metapp.Exp.of_bool
                           (Clangml_config.version.major >= 10)]])
             ->
             Pointer
               (of_type_loc (Clang__bindings.ext_attrs_get_deref_type cursor))
         | ((PragmaClangBSSSection)[@if
                                     [%meta
                                       Metapp.Exp.of_bool
                                         (Clangml_config.version.major >= 5)]])
             ->
             PragmaClangBSSSection
               (Clang__bindings.ext_attrs_get_name cursor)
         | ((PragmaClangDataSection)[@if
                                      [%meta
                                        Metapp.Exp.of_bool
                                          (Clangml_config.version.major >= 5)]])
             ->
             PragmaClangDataSection
               (Clang__bindings.ext_attrs_get_name cursor)
         | ((PragmaClangRelroSection)[@if
                                       [%meta
                                         Metapp.Exp.of_bool
                                           (Clangml_config.version.major >=
                                              10)]])
             ->
             PragmaClangRelroSection
               (Clang__bindings.ext_attrs_get_name cursor)
         | ((PragmaClangRodataSection)[@if
                                        [%meta
                                          Metapp.Exp.of_bool
                                            (Clangml_config.version.major >=
                                               5)]])
             ->
             PragmaClangRodataSection
               (Clang__bindings.ext_attrs_get_name cursor)
         | ((PragmaClangTextSection)[@if
                                      [%meta
                                        Metapp.Exp.of_bool
                                          (Clangml_config.version.major >= 5)]])
             ->
             PragmaClangTextSection
               (Clang__bindings.ext_attrs_get_name cursor)
         | PtGuardedBy ->
             PtGuardedBy
               (expr_of_cxcursor (Clang__bindings.ext_attrs_get_arg cursor))
         | ((RISCVInterrupt)[@if
                              [%meta
                                Metapp.Exp.of_bool
                                  (Clangml_config.version.major >= 7)]])
             ->
             RISCVInterrupt
               (Clang__bindings.ext_riscvinterrupt_attr_get_interrupt cursor)
         | ((ReleaseCapability)[@if
                                 [%meta
                                   Metapp.Exp.of_bool
                                     (((Clangml_config.version.major),
                                        (Clangml_config.version.minor)) >=
                                        (3, 5))]])
             ->
             ReleaseCapability
               {
                 spelling =
                   (Clang__bindings.ext_release_capability_get_spelling
                      cursor);
                 args =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_acquire_capability_attr_get_args
                          cursor))
                      |> (List.map expr_of_cxcursor))
               }
         | ((ReleaseHandle)[@if
                             [%meta
                               Metapp.Exp.of_bool
                                 (Clangml_config.version.major >= 10)]])
             ->
             ReleaseHandle (Clang__bindings.ext_attrs_get_handle_type cursor)
         | ReqdWorkGroupSize ->
             ReqdWorkGroupSize
               {
                 x_dim = (Clang__bindings.ext_attrs_get_xdim cursor);
                 y_dim = (Clang__bindings.ext_attrs_get_ydim cursor);
                 z_dim = (Clang__bindings.ext_attrs_get_zdim cursor)
               }
         | ((RequiresCapability)[@if
                                  [%meta
                                    Metapp.Exp.of_bool
                                      (((Clangml_config.version.major),
                                         (Clangml_config.version.minor)) >=
                                         (3, 5))]])
             ->
             RequiresCapability
               {
                 spelling =
                   (Clang__bindings.ext_requires_capability_get_spelling
                      cursor);
                 args =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_acquire_capability_attr_get_args
                          cursor))
                      |> (List.map expr_of_cxcursor))
               }
         | ((Restrict)[@if
                        [%meta
                          Metapp.Exp.of_bool
                            (((Clangml_config.version.major),
                               (Clangml_config.version.minor)) >= (3, 7))]])
             -> Restrict (Clang__bindings.ext_restrict_get_spelling cursor)
         | ReturnTypestate ->
             ReturnTypestate
               (Clang__bindings.ext_return_typestate_attr_get_state cursor)
         | Section ->
             Section
               {
                 spelling = (Clang__bindings.ext_section_get_spelling cursor);
                 name = (Clang__bindings.ext_attrs_get_name cursor)
               }
         | Sentinel ->
             Sentinel
               {
                 sentinel =
                   (Clang__bindings.ext_sentinel_attr_get_sentinel cursor);
                 null_pos =
                   (Clang__bindings.ext_sentinel_attr_get_null_pos cursor)
               }
         | SetTypestate ->
             SetTypestate
               (Clang__bindings.ext_set_typestate_attr_get_new_state cursor)
         | SharedTrylockFunction ->
             SharedTrylockFunction
               {
                 success_value =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_success_value cursor));
                 args =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_acquire_capability_attr_get_args
                          cursor))
                      |> (List.map expr_of_cxcursor))
               }
         | ((Suppress)[@if
                        [%meta
                          Metapp.Exp.of_bool
                            (Clangml_config.version.major >= 5)]])
             ->
             Suppress
               (Clang__utils.list_of_iter
                  (Clang__bindings.ext_suppress_attr_get_diagnostic_identifiers
                     cursor))
         | TLSModel ->
             TLSModel (Clang__bindings.ext_tlsmodel_attr_get_model cursor)
         | ((Target)[@if
                      [%meta
                        Metapp.Exp.of_bool
                          (((Clangml_config.version.major),
                             (Clangml_config.version.minor)) >= (3, 8))]])
             ->
             Target (Clang__bindings.ext_target_attr_get_features_str cursor)
         | TestTypestate ->
             TestTypestate
               (Clang__bindings.ext_test_typestate_attr_get_test_state cursor)
         | ((TryAcquireCapability)[@if
                                    [%meta
                                      Metapp.Exp.of_bool
                                        (((Clangml_config.version.major),
                                           (Clangml_config.version.minor)) >=
                                           (3, 5))]])
             ->
             TryAcquireCapability
               {
                 spelling =
                   (Clang__bindings.ext_try_acquire_capability_get_spelling
                      cursor);
                 success_value =
                   (expr_of_cxcursor
                      (Clang__bindings.ext_attrs_get_success_value cursor));
                 args =
                   ((Clang__utils.list_of_iter
                       (Clang__bindings.ext_acquire_capability_attr_get_args
                          cursor))
                      |> (List.map expr_of_cxcursor))
               }
         | TypeTagForDatatype ->
             TypeTagForDatatype
               {
                 argument_kind =
                   (Clang__bindings.ext_attrs_get_argument_kind cursor);
                 matching_ctype =
                   (of_type_loc
                      (Clang__bindings.ext_type_tag_for_datatype_attr_get_matching_ctype
                         cursor));
                 layout_compatible =
                   (Clang__bindings.ext_type_tag_for_datatype_attr_get_layout_compatible
                      cursor);
                 must_be_null =
                   (Clang__bindings.ext_type_tag_for_datatype_attr_get_must_be_null
                      cursor)
               }
         | TypeVisibility ->
             TypeVisibility
               (Clang__bindings.ext_type_visibility_attr_get_visibility
                  cursor)
         | Unavailable ->
             Unavailable (Clang__bindings.ext_attrs_get_message cursor)
         | Unused -> Unused (Clang__bindings.ext_unused_get_spelling cursor)
         | ((UseHandle)[@if
                         [%meta
                           Metapp.Exp.of_bool
                             (Clangml_config.version.major >= 10)]])
             -> UseHandle (Clang__bindings.ext_attrs_get_handle_type cursor)
         | Uuid -> Uuid (Clang__bindings.ext_uuid_attr_get_guid cursor)
         | VecTypeHint ->
             VecTypeHint
               (of_type_loc
                  (Clang__bindings.ext_vec_type_hint_attr_get_type_hint
                     cursor))
         | Visibility ->
             Visibility
               (Clang__bindings.ext_visibility_attr_get_visibility cursor)
         | ((WarnUnusedResult)[@if
                                [%meta
                                  Metapp.Exp.of_bool
                                    (Clangml_config.version.major >= 10)]])
             ->
             WarnUnusedResult
               {
                 spelling =
                   (Clang__bindings.ext_warn_unused_result_get_spelling
                      cursor);
                 message = (Clang__bindings.ext_attrs_get_message cursor)
               }
         | WeakRef -> WeakRef (Clang__bindings.ext_attrs_get_aliasee cursor)
         | ((WebAssemblyExportName)[@if
                                     [%meta
                                       Metapp.Exp.of_bool
                                         (Clangml_config.version.major >= 10)]])
             ->
             WebAssemblyExportName
               (Clang__bindings.ext_web_assembly_export_name_attr_get_export_name
                  cursor)
         | ((WebAssemblyImportModule)[@if
                                       [%meta
                                         Metapp.Exp.of_bool
                                           (Clangml_config.version.major >= 8)]])
             ->
             WebAssemblyImportModule
               (Clang__bindings.ext_web_assembly_import_module_attr_get_import_module
                  cursor)
         | ((WebAssemblyImportName)[@if
                                     [%meta
                                       Metapp.Exp.of_bool
                                         (Clangml_config.version.major >= 8)]])
             ->
             WebAssemblyImportName
               (Clang__bindings.ext_web_assembly_import_name_attr_get_import_name
                  cursor)
         | WorkGroupSizeHint ->
             WorkGroupSizeHint
               {
                 x_dim = (Clang__bindings.ext_attrs_get_xdim cursor);
                 y_dim = (Clang__bindings.ext_attrs_get_ydim cursor);
                 z_dim = (Clang__bindings.ext_attrs_get_zdim cursor)
               }
         | ((XRayInstrument)[@if
                              [%meta
                                Metapp.Exp.of_bool
                                  (((Clangml_config.version.major),
                                     (Clangml_config.version.minor)) >=
                                     (3, 9))]])
             ->
             XRayInstrument
               (Clang__bindings.ext_xray_instrument_get_spelling cursor)
         | ((XRayLogArgs)[@if
                           [%meta
                             Metapp.Exp.of_bool
                               (Clangml_config.version.major >= 5)]])
             ->
             XRayLogArgs
               (Clang__bindings.ext_xray_log_args_attr_get_argument_count
                  cursor)
         | other -> Other other])]
